apiVersion: v1
kind: Service
metadata:
  name: apache-svc
  labels:
    app: apache
spec:
  ports:
   - nodePort: 31000
     port: 80
     targetPort: 80
  selector:
    app: apache
    type: LoadBalancer
---
apiVersion: v1
kind: PersistenVolumeClaim
metadata:
  name: apache-pvc
  labels:
    app: apache
spec:
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-pod
  labels: 
    app: apache
spec:
  selector:
   matchLabels:
     app: apache
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: apache
   spec:
     containers:
      - image: vimal13/apache-webserver-php
        name: apache
        ports:
         - containerPort: 31000
           name: apache
        volumeMounts:
          - name: apache-vol
            mountPath: /var/www/html
     volumes:
      - name: apache-vol
        persistentVolumeClaim:
          claimNmae: apache-pvc
